print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/ci3-122-mac2/BrokenDonut_Outer/BrokenDonut/Assets/Maya_Assets/BrokenDonut_Recreate_3.mb"`)
{		
	file -o "/Users/ci3-122-mac2/BrokenDonut_Outer/BrokenDonut/Assets/Maya_Assets/BrokenDonut_Recreate_3.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/ci3-122-mac2/BrokenDonut_Outer/BrokenDonut/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/ci3-122-mac2/BrokenDonut_Outer/BrokenDonut/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/ci3-122-mac2/BrokenDonut_Outer/BrokenDonut/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
